export const PROJECT_ROLE_OPTIONS = [
  { label: "Project Manager", value: "Project Manager" },
  { label: "Team Lead", value: "Team Lead" },
  { label: "Developer", value: "Developer" },
  { label: "Senior Developer", value: "Senior Developer" },
  { label: "Junior Developer", value: "Junior Developer" },
  { label: "Frontend Developer", value: "Frontend Developer" },
  { label: "Backend Developer", value: "Backend Developer" },
  { label: "Full Stack Developer", value: "Full Stack Developer" },
  { label: "UI/UX Designer", value: "UI/UX Designer" },
  { label: "QA Engineer", value: "QA Engineer" },
  { label: "DevOps Engineer", value: "DevOps Engineer" },
  { label: "Business Analyst", value: "Business Analyst" },
  { label: "Scrum Master", value: "Scrum Master" },
  { label: "Product Owner", value: "Product Owner" },
  { label: "Member", value: "Member" },
  { label: "Lead", value: "Lead" },
  { label: "Manager", value: "Manager" },
  { label: "Tester", value: "Tester" },
  { label: "Designer", value: "Designer" },
];
