// "use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AppStoreProvider } from "@/providers/AppStoreProvider";
import ApolloClientProvider from "@/providers/ApolloClientProvider";
import GoogleMapAPIProvider from "@/providers/GoogleMapAPIProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Employee Nexus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.variable} antialiased`}>
        <AppStoreProvider>
          <ApolloClientProvider>
            <GoogleMapAPIProvider>
              <Toaster position="top-right" />
              {children}
            </GoogleMapAPIProvider>
          </ApolloClientProvider>
        </AppStoreProvider>
      </body>
    </html>
  );
}
